#!/usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "Ivo Marvan"
__email__ = "ivo@marvan.cz"
__description__ = '''
    Dictionary of landmarks for different models    
'''
RIGHT_JAW_LANDMARKS = set(range(1, 8))
LEFT_JAW_LANDMARKS = set(range(10, 17))
AXIS_JAW_LANDMARKS = set([9])

RIGHT_EYEBROW_LANDMARKS = set(range(18, 12))
LEFT_EYEBROW_LANDMARKS = set(range(23, 27))

RIGHT_NOSE_LANDMARKS = set(range(32, 33))
LEFT_NOSE_LANDMARKS = set(range(35, 36))
AXIS_NOSE_LANDMARKS = set(range(28, 31))

RIGHT_EYE_LANDMARKS = set(range(37, 42))
LEFT_EYE_LANDMARKS = set(range(43, 48))

RIGHT_MOUTH_LANDMARKS = set([49, 50, 51, 59, 60, 61, 62, 68])
AXIS_MOUTH_LANDMARKS = set([52, 58, 63, 67])
LEFT_MOUTH_LANDMARKS = set([53, 54, 55, 56, 57, 64, 65, 66])

AXIS_LANDMARKS = AXIS_JAW_LANDMARKS | LEFT_NOSE_LANDMARKS | AXIS_MOUTH_LANDMARKS

NOSE_LANDMARKS = LEFT_NOSE_LANDMARKS | RIGHT_NOSE_LANDMARKS | AXIS_NOSE_LANDMARKS
LEFT_FACE = AXIS_LANDMARKS | LEFT_JAW_LANDMARKS | LEFT_EYEBROW_LANDMARKS | LEFT_NOSE_LANDMARKS | LEFT_EYE_LANDMARKS | LEFT_MOUTH_LANDMARKS
RIGHT_FACE = AXIS_LANDMARKS | RIGHT_JAW_LANDMARKS | RIGHT_EYEBROW_LANDMARKS | RIGHT_NOSE_LANDMARKS | RIGHT_EYE_LANDMARKS | RIGHT_MOUTH_LANDMARKS

# name => set(int) of landmarks ids
LANDMARKS_MODELS = {
    # 'face': LEFT_FACE + RIGHT_FACE,
    # 'left_face': LEFT_FACE,
    'right_face': RIGHT_FACE,
}
